name: Build Program

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build and Execute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-07-17

      - name: Install Ziren toolchain
        run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ProjectZKM/toolchain/refs/heads/main/setup.sh | sh
      - name: Install Dependencies
        run: sudo apt install protobuf-compiler
      - name: Execute the program
        run: |
          source ~/.zkm-toolchain/env && cd host && cargo run --release -- --execute
